name: travel_wisata_lokal
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.9.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^7.0.0
  latlong2: ^0.9.0

  # Database SQLite
  sqflite: ^2.3.0
  path_provider: ^2.1.2
  path: ^1.8.3

  # Google Maps
  google_maps_flutter: ^2.5.0

  # Image Picker
  image_picker: ^1.0.7

  # Permission (lokasi & storage)
  permission_handler: ^11.1.0

  # ðŸ‘‰ DITAMBAHKAN (UNTUK LOKASI USER)
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  http: ^1.2.0
  # State management
  provider: ^6.1.2

  # Icon iOS style
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
